org: traveller
app: aws-node-express-api-app
service: traveller
provider:
  name: aws
  timeout: 30
  memorySize: 128
  runtime: nodejs14.x
  region: us-east-1
  environment:
    MONGODB_URI: "mongodb://localhost:27017/traveller"

functions: ${file(serverless/functions.yml)}

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false
